find_package (Sophus REQUIRED)
find_package(FMT REQUIRED)
include_directories(${Sophus_INCLUDE_DIRS})
list(APPEND ALL_TARGET_LIBRARIES ${Sophus_LIBRARIES} fmt)
list(APPEND INCLUDE_DIR_LIST ${Sophus_INCLUDE_DIRS})
